#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 yamakouAO
# SPDX-License-Identifier: BSD-3-Clause

import sys

vals = []


for line in sys.stdin:
    for v in line.split():
        vals.append(float(v))

A, B, C, D = vals
print(A * D - B * C)
