#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 yamakouAO
# SPDX-License-Identifier: BSD-3-Clause

import sys

vals = []


for line in sys.stdin:
    for v in line.split():
        vals.append(float(v))

A, B, C, D, E, F, G, H, I = vals
AEI = A * E * I
BFG = B * F * G
CHD = C * H * D
AHF = A * H * F
BDI = B * D * I
CEG = C * E * G

print(AEI + BFG + CHD - AHF - BDI - CEG)
